# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201227_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsort',
            name='products_image',
            field=models.ImageField(default=True, upload_to='image'),
            preserve_default=False,
        ),
    ]
