# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-01-12 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210108_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(default=True, upload_to='products'),
            preserve_default=False,
        ),
    ]
